DROP DATABASE IF EXISTS awb;
CREATE DATABASE awb;
USE awb;
CREATE TABLE IF NOT EXISTS images (
    id INT AUTO_INCREMENT PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    width INT NOT NULL,
    height INT NOT NULL,
    sift LONGBLOB NOT NULL
);
